version: "3"

services:
    php_fpm:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: blog_api_php_fpm
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        networks:
            - custom_net
        volumes:
            - ./laravel:/var/www
            - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        depends_on:
            - mysql
            - redis
    nginx:
        image: nginx:alpine
        container_name: blog_api_nginx
        working_dir: /usr/share/nginx/blog_api
        restart: unless-stopped
        tty: true
        networks:
            - custom_net
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./laravel:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    mysql:
        image: mysql:5.7.22
        container_name: blog_api_mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        networks:
            - custom_net
        environment:
            - MYSQL_DATABASE=blog_api
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
        volumes:
            - ./mysql/dbdata:/var/lib/mysql/
            - ./mysql/my.cnf:/etc/mysql/my.cnf
    redis:
        container_name: blog_api_redis
        image: redis:4.0
        networks:
            - custom_net
        ports:
            - "6379:6379"

networks:
    custom_net:
        driver: bridge
#        ipam:
#            config:
#                - subnet: 192.168.220.0/24 # for Xdebug connect to the host machine